# Generated by Django 4.0.2 on 2022-02-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_images_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Images', 'verbose_name_plural': 'Images'},
        ),
    ]
